import os
from dotenv import load_dotenv

load_dotenv()

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
YANDEX_GPT_API_KEY = os.getenv("YANDEX_GPT_API_KEY")
YANDEX_STORAGE_BUCKET_NAME = os.getenv("YANDEX_STORAGE_BUCKET_NAME")
YANDEX_STORAGE_OBJECT_KEY = os.getenv("YANDEX_STORAGE_OBJECT_KEY")
YANDEX_ACCESS_KEY = os.getenv("YANDEX_ACCESS_KEY")
YANDEX_SECRET_KEY = os.getenv("YANDEX_SECRET_KEY")
